fail test

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -29,4 +29,6 @@ jobs:
       run: go build -v ./...
 
     - name: Test
-      run: go test -v ./...
+      # run: go test -v ./...
+      # simulattion of failure test
+      run: exit 1
